### ISSUE TITLE
Support for Redis cluster commands

### ISSUE THREAD

**Issue by pims** [tidwall/uhaha#1]
Hi 👋 

This is an excellent project!
I was playing around with the ticket server example and wanted to suggest a minor change.

I recently discovered that `redis-cli` supports an additional `-c` flag to configure it in [cluster-mode](https://github.com/redis/redis/blob/unstable/src/redis-cli.c#L1756):
```
-c    Enable cluster mode (follow -ASK and -MOVED redirections).
```

so I made a small change:
```diff
diff --git a/uhaha.go b/uhaha.go
index 4e39375..7a96854 100644
--- a/uhaha.go
+++ b/uhaha.go
@@ -988,7 +988,9 @@ func errRaftConvert(ra *raftWrap, err error) error {
        if err == raft.ErrNotLeader {
                leader := getLeaderBroadcastAddr(ra)
                if leader != "" {
-                       return fmt.Errorf("TRY %s", leader)
+                       parts := strings.Split(leader, "]") # TODO: proper parsing
+                       return fmt.Errorf("MOVED foo 127.0.0.1%s", parts[1])
```

which shows the following behavior with `redis-cli`
```
redis-cli -p 11003 -c
127.0.0.1:11003> RAFT LEADER
"[::]:11003"
127.0.0.1:11003> TICKET
"6"
# trigger a leader election
127.0.0.1:11003> TICKET
-> Redirected to slot [0] located at 127.0.0.1:11002
"9"
127.0.0.1:11002>
```

which is pretty convenient for testing with `redis-cli`.

Being a little greedy, I tried to reproduce this by connecting from a go redis client. It looks like only client that implements the redis cluster protocol support the `MOVED` command.

```go
rdb := redis.NewClusterClient(&redis.ClusterOptions{
   Addrs: []string{":11001", ":11002", ":11003"},
})
```
and seeing a somewhat expected:
```
ERR unknown command 'cluster'
```

My understanding is that when starting the initial connection, the client asks a redis server node for the slot partitioning, in order to more efficiently route requests directly to the node responsible for that slot range.

I'd be curious to hear your thoughts on supporting the `CLUSTER SLOTS` command, and assigning all slots to the current leader, with the format described at [https://redis.io/commands/cluster-slots](https://redis.io/commands/cluster-slots)

I'm not sure if it's possible to add such a behavior with a dedicated command `conf.AddIntermediateCommand("cluster", cmdCLUSTER)`.

The goal is to have clients connect to a single address and follow redirections from `-MOVED …` errors. The semantics _look_ similar, even if with uhaha, a single node covers all slots.

**Comment by tidwall** [comment]
Hi. I'm glad you like the project. :)

I intentionally designed Uhaha to use `TRY` instead of `ASK` or `MOVED`.
I originally went down the path that you are suggesting with the Finn project, which was later transitioned to Uhaha. But at the time, in 2016, I found the endeavor to be rather confusing. 

The `MOVED`, `ASK`, `ASKING` that Redis introduced was very specific to their slot-based system and I thought it didn't make as much for a Raft Leader/Follower model. Also, there wasn't a lot of client support for clusters at the time. 

So I decided to use the `TRY` response (instead of `ASK`), which is more general in that it doesn't care about slots, etc. 

That being said, if the client support is better at this point, I could see value in supporting Redis cluster error messages.

Perhaps with starting up a Uhaha application with a `-c` flag, or maybe when the server receives a `CLUSTER` command from the client, the errors can go from `TRY` to `ASK` or `MOVED`, etc.

Also, it may be of interest to you that the [Uhaha Go client](https://github.com/tidwall/uhatools) I wrote supports following the leader from TRY errors.

**Comment by tidwall** [comment]
The more I think about it the more I like the idea, I'm gonna investigate further.

**Comment by tidwall** [comment]
I added the branch `redis-cluster`, which has basic Redis Cluster support.

It tests out of the box with `redis-cli -c`, https://github.com/go-redis/redis, and https://github.com/mitsuhiko/redis-rs

**Comment by pims** [comment]
This looks excellent. I’ll give it a try tonight.

**Comment by tidwall** [comment]
I added the changes to master.
