### ISSUE TITLE
multi group raft

### ISSUE THREAD

**Issue by carr123** [tidwall/uhaha#8]
does it support multi group raft ?
thanks.

**Comment by FZambia** [comment]
As far as I know Hashicorp Raft implementation [does not support multi-raft](https://github.com/hashicorp/raft/issues/290) –  so uhaha most probably inherits this. I am just looking around in Raft ecosystem – I suppose it's possible to add multi-group raft on top of Etcd implementation ([not well documented](https://github.com/etcd-io/etcd/issues/4932) how though). Also found an interesting library which supports multi-Raft - [dragonboat](https://github.com/lni/dragonboat), may be an option to consider as an underlying Raft lib here.

**Comment by tidwall** [comment]
@FZambia Have you had an opportunity to use Dragonboat? It looks interesting on the surface, but I have zero experience with it.

**Comment by tidwall** [comment]
If the need for multi-group is higher performance then I should point out that I did a few tricks with Uhaha. The biggest one is that Uhaha multiplexes the raft apply operation when multiple clients are concurrently writing data. This is inspired by [nutcracker pipelining](https://github.com/twitter/twemproxy#pipelining), and it helps me get millions of writes per second for Uhaha. 

Here's the relevant code 
https://github.com/tidwall/uhaha/blob/4743869057399e3793c1a37edc30e4cd2188fc37/uhaha.go#L1121-L1181

That said, I wonder if using Dragonboat under the hood wouldn't be a more optimal solution?

**Comment by FZambia** [comment]
> Have you had an opportunity to use Dragonboat? It looks interesting on the surface, but I have zero experience with it.

I am just looking around currently, had no practical experience with any Raft library. Mostly learning and trying to apply it to my case – I need a PUB/SUB system with in-memory STREAMSs and in-memory HASH (mostly a subset of Redis functionality with Raft goodies which I could tune for a specific use case).

An interesting observation is that author of Dragonboat currently contributes into https://github.com/matrixorigin/matrixcube - which also provides multi-raft and built on top of etcd Raft implementation. In general I think sticking to etcd Raft may be also a good/safe decision since it's already a building block of several large projects. But hard to say whether it's worth it or not.

**Comment by danthegoodman1** [comment]
Random interested user chiming in here:

I think that the multi-group speaks more to partitionability rather than just performance (although it is a side effect). Also being able to do more advanced features like geopartitioning data and such (but maybe that's a more complex case where something like dragonboat is more appropriate).

While for something like a KV store, a single leader is fine with a fast disk, but for something more compute-intensive then it would be far more beneficial to divide the load across many leaders as the bottleneck is not disk or network, but rather CPU time.

For example if some process can take upwards of 10ms to calculate, then that greatly reduces the throughput of the system due to the linearlizability guarantees to ~100op/s. However if we could partition into 100 ranges, in an ideal case we should be able to reach ~10kop/s because the raft log will not be blocking every request.

Of course the above is all assuming I understand raft and multi-groups correctly :)
